### ISSUE TITLE
UnicodeDecodeError when installing on python 3 under windows

### ISSUE THREAD

**Issue by pauloyster** [tsroten/dragonmapper#9]
No problems with python 2 on windows, but installing for 3.4 gives the following traceback:

```
File "<string>", line 17, in <module>
   File "C:\Users\Gal\AppData\Local\Temp\pip_build_Gal\dragonmapper\setup.py", line 24, in <module>
     readme = open_file('README.rst')
   File "C:\Users\Gal\AppData\Local\Temp\pip_build_Gal\dragonmapper\setup.py", line 22, in open_file
     return f.read()
   File "C:\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
 UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1282: character maps to <undefined>
 Complete output from command python setup.py egg_info:
 Traceback (most recent call last):
File "<string>", line 17, in <module>

File "C:\Users\Gal\AppData\Local\Temp\pip_build_Gal\dragonmapper\setup.py", line 24, in <module>

 readme = open_file('README.rst')

File "C:\Users\Gal\AppData\Local\Temp\pip_build_Gal\dragonmapper\setup.py", line 22, in open_file

 return f.read()

File "C:\Anaconda3\lib\encodings\cp1252.py", line 23, in decode

 return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1282: character maps to <undefined>
```

**Comment by tsroten** [comment]
@pauloyster Thanks for reporting this error! Do you mind trying this and telling me what happens?

1. Download [DragonMapper's `README.rst`](https://raw.githubusercontent.com/tsroten/dragonmapper/develop/README.rst).

2. Run the following:
```python
$ python3
>>> readme = 'path_to_readme_file_you_downloaded'
>>> with open(readme, encoding='utf-8'):
...    f.read()
```

If it works, you should see something like this:
```"=============\nDragon Mapper\n=============\n\n.. [abbreviated for the sake of readability]"```

**Comment by pauloyster** [comment]
File opens and reads ok (with utf-8 encoding).

**Comment by tsroten** [comment]
Thanks. I will make `setup.py` use `io.open()` instead of `open()` so that both Python 2 and 3 will open `README.rst` in UTF-8.

**Comment by pauloyster** [comment]
Thanks!

BTW, same goes for hanzidentifier.

**Comment by tsroten** [comment]
Hanzi Identifier has been updated as well. Thanks again!
